config/routes.rb
Rails.application.routes.draw do

  get 'user', to: 'users#me', as: 'current_user'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do 
    root "devise/sessions#new"
    post 'cover', to: 'users#cover', as: :cover
    post 'profile_picture', to: 'users#profile_picture', as: :profile_picture
  end 
  resources :users, only: [:show, :update] 
  
  resources :homes, only: [:index]
  resources :posts, except: [:show, :index] do 
    get 'comments', to: 'comments#create'
    resources :comments, only: [:destroy, :edit, :update]
  end   
  resources :friends, only: [:index, :new, :create, :destroy]
  get 'likes', to: 'likes#create', as: :likes
  delete 'likes', to: 'likes#destroy'
  
  get 'users', to: redirect('users/sign_up')


end 

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def index 
    # Fetching all friends and friend requests for current user 
    @sent_requests = Friend.where("sender_id = ? AND accepted = ?", current_user.id, false)
    @received_requests = Friend.where(receiver: current_user).where(accepted: false)
    friend_requests = current_user.requests_received.pluck(:sender_id) + current_user.requests_sent.pluck(:receiver_id)
    

    if friend_requests.any? 
      @users = User.not_me(current_user).where('id NOT IN (?)', friend_requests)
    else  
      @users = User.not_me(current_user)
    end 
    
  end 

  def new 
    # Creating a new friend request 
    params = CGI.parse(URI.parse(request.url).query)

    receiver = User.find_by('id = ?', params["receiver"])
    new_friend_request = Friend.new(sender: current_user, receiver: receiver) 
    if new_friend_request.save!
      flash[:success] = 'Friend request sent!'
      NotifChannel.broadcast_to(receiver, user: current_user); 
      redirect_to friends_path
    else 
      flash.now[:error] = 'friend request couldnt be sent unfortunately.'
      render :index  
    end 
  end 

  def destroy 
    friend_request = Friend.find(params[:id])

    if friend_request.destroy 
      flash[:success] = "Request Unsent."
      
    else 
      flash[:error] = "Unable to undo request."
    end 
    redirect_to friends_path
  end 

  def create 
    params = CGI.parse(URI.parse(request.url).query)
    
    friend_request = Friend.find_by(id: params["friend_request_id"])
    friend_request.accepted = true 
    if friend_request.save 
      flash[:success] = 'Friend Request accepted.'
      redirect_to friends_path
    else 
      flash.now[:error] = 'Friend request could not be accepted unfortunately.'
      render :index
    end 
    
  end 

  private





end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<div class="success-error">
  <%= flash[:success] %>
  <%= flash.now[:error] %>
</div>

<div class="friends-container bg-white border border-solid border-gray-300 w-1/2 sm:w-1/3 md:w-1/4 lg:w-1/5 flex flex-col shadow m-2">

  <% if @received_requests.any? %>
    <span class="received-text text-xs pl-2">Received Requests</span>
    <% @received_requests.each do |req| %>
      <div class="received-div flex w-full p-2">
        
        <%= link_to user_path req.sender do %>
          <div class="profile-pic flex items-center pt-2" >  
            <% if req.sender.profile_picture.attached? %>
              <%= image_tag req.sender.profile_picture, class: 'rounded-full h-9 w-10' %>
            <% else %>
              <img x="0" y="0" class="rounded-full h-9 w-10" height="100%" preserveAspectRatio="xMidYMid slice" width="100%" src=<%= User.default_profile_pic %> >
            <% end %>
          </div>
        <% end %>
        <div class="username-and-request flex flex-col pl-4 w-full">
          <%= link_to user_path req.sender do %>
            <p class="font-medium"> <%= current_user.formatted_name %> </p>
          <% end %>
          <div class="received-request w-full flex space-x-2">
            <!-- Button to accept friend -->
            <%= link_to friends_path(friend_request_id: req.id), method: :post, class: 'w-1/2' do %>
              <button class="py-1 w-full rounded text-white font-medium bg-blue-600">Accept</button>
            <% end %>
            <!-- Button to delete friend -->
            <%= link_to req, method: :delete, class: 'w-1/2' do %>
              <button class="py-1 w-full rounded bg-gray-100 text-black font-medium">Cancel</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="w-full flex justify-center mt-2"><hr class="w-4/5"></div>
  <% end %>

  <% if @sent_requests.any? %>
    <span class="text-xs pl-2 pt-2">Sent Friend requests</span>
    <% @sent_requests.each do |req| %>
      <div class="flex w-full p-2">
        <%= link_to user_path(req.receiver) do %>
          <div class="profile-pic flex items-center pt-2" > 
            <% if req.receiver.profile_picture.attached? %> 
              <%= image_tag req.receiver.profile_picture, class: 'rounded-full h-9 w-10' %>
            <% else %>     
              <img x="0" y="0" class="rounded-full h-9 w-10" height="100%" preserveAspectRatio="xMidYMid slice" width="100%" src=<%= User.default_profile_pic %>> 
            <% end %>
          </div>
        <% end %>
        <div class="username-and-request flex flex-col pl-4 w-full">
          <%= link_to user_path req.receiver do %>
            <p class="font-medium"> <%= req.receiver.formatted_name %> </p>
          <% end %>
          <div class="sent-request w-full">
            <%= link_to req, method: :delete do %>
              <button class="bg-gray-200 text-black font-semibold w-full rounded py-1">Cancel Friend request</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <div class="w-full flex justify-center mt-2"><hr class=" w-4/5"></div>
  <% end %>

  <% if @users.any? %>
    <span class="text-xs pl-2 pt-2">People you may know</span>
    <% @users.each do |user| %>
      <div class="users flex w-full p-2">
        <%= link_to user_path user, class: 'pt-2' do %>
          <div class="profile-pic flex items-center pt-4" >
            <% if user.profile_picture.attached? %> 
              <%= image_tag user.profile_picture, class: 'rounded-full h-9 w-10' %>  
            <% else %> 
              <img x="0" y="0" class="rounded-full h-9 w-10" height="100%" preserveAspectRatio="xMidYMid slice" width="100%" src=<%= User.default_profile_pic %> 
            <% end %> >
          </div>
        <% end %>
          <div class="username-and-request flex flex-col pl-4 w-full">
            <%= link_to user_path user do %>
              <p class="username font-medium"> <%= user.formatted_name%> </p>
            <% end %>
            <div class="new-request w-full">
              <%= link_to new_friend_path(receiver: user.id) do %>
                <button class="bg-blue-700 text-white font-semibold w-full rounded py-1">Send Friend Request</button>
              <% end %>
            </div>
          </div>
      </div>
    <% end %>
  <% end %>

</div>

<div class="w-screen h-screen md:absolute top-0 md:flex items-center justify-center z-under">
      <div class="flex flex-col items-center">
        <svg class="w-28 h-28" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 112 112">
          <defs>
            <clipPath id="a">
              <circle cx="72.58" cy="53.81" r="12.08" fill="none"></circle>
            </clipPath>
          </defs>
          <g clip-path="url(#a)">
            <circle cx="72.58" cy="53.81" r="12.08" fill="#1876f2"></circle>
            <circle cx="62.18" cy="40.55" r="14.72" fill="#a4a7ab"></circle>
            <circle cx="88.92" cy="39.27" r="14.72" fill="#a4a7ab"></circle>
          </g>
          <path d="M27.37 17.56h11.3a3.84 3.84 0 013.84 3.84v15h-19v-15a3.84 3.84 0 013.86-3.84z"></path>
          <rect width="19" height="24.75" x="23.52" y="26.9" fill="#90c3ff" rx="8.65"></rect>
          <path fill="#a4a7ab" d="M18.87 55.28h28.3a7 7 0 017 7v37.36H11.92V62.23a7 7 0 016.95-6.95z"></path>
          <path fill="#64676b" d="M68.63 68.28h5.06A26.12 26.12 0 0199.8 94.4v5.25H42.51V94.4a26.12 26.12 0 0126.12-26.12z"></path>
          <circle cx="66.32" cy="35.2" r="7.55" fill="#a4a7ab"></circle>
        </svg>
        <span class="text-xl font-semibold">
          Select people's names to preview their profile.
        </span>
      </div>
</div>