config/routes.rb
Rails.application.routes.draw do

  get 'user', to: 'users#me', as: 'current_user'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do 
    root "devise/sessions#new"
    post 'cover', to: 'users#cover', as: :cover
    post 'profile_picture', to: 'users#profile_picture', as: :profile_picture
  end 
  resources :users, only: [:show, :update] 
  
  resources :homes, only: [:index]
  resources :posts, except: [:show, :index] do 
    get 'comments', to: 'comments#create'
    resources :comments, only: [:destroy, :edit, :update]
  end   
  resources :friends, only: [:index, :new, :create, :destroy]
  get 'likes', to: 'likes#create', as: :likes
  delete 'likes', to: 'likes#destroy'
  
  get 'users', to: redirect('users/sign_up')


end 

app/models/user.rb
class User < ApplicationRecord

  include UsersHelper

  attr_accessor :login
  attr_reader :genders 

  after_create :send_mail

  has_many :posts, dependent: :destroy  
  has_one_attached :cover, dependent: :destroy  
  has_one_attached :profile_picture, dependent: :destroy 
  has_many_attached :images 
  has_many :requests_sent, class_name: 'Friend', foreign_key: :sender, dependent: :destroy 
  has_many :requests_received, class_name: 'Friend', foreign_key: :receiver, dependent: :destroy 
  has_many :likes, dependent: :destroy  
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments, dependent: :destroy 
  has_many :comment_posts, through: :comments, source: :post 

  scope :not_me, ->(me) { where('id <> ?', me.id) }



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         authentication_keys: [:login]
  devise :omniauthable, omniauth_providers: %i[facebook]

  
  # VALIDATIONS 

  validates :gender, :first, :last, presence: true, unless: :updating? 
  validates_format_of :email, with: /\A([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})\z/, unless: :blank? 

  def send_mail 
    if self.persisted? && self.valid?(:email )
      UserMailer.with(user: self).after_sign_up_email.deliver_now
    end 
  end 

  def blank? 
    email == '' ? true : false 
  end 

  def updating? 
    self.persisted? ? true : false 
  end 

  def friends 
    requests_received.where(accepted: true).pluck(:sender_id) + requests_sent.where(accepted: true).pluck(:receiver_id) + [self.id]
  end 

  def my_friends 
    array = []
    received = requests_received.where(accepted: true).includes(:sender)
    sent = requests_sent.where(accepted: true).includes(:receiver)
    sent.each do |req| 
      array << req.receiver
    end 
    received.each do |req| 
      array << req.sender
    end 
    array
  end 

  # Open metaclass and define the following method 
  class << self 
    def find_for_database_authentication warden_condition
      conditions = warden_condition.dup
      login = conditions.delete(:login)
      where(conditions).where(
        ["lower(username) = :value OR lower(email) = :value",
        { value: login.strip.downcase}]).first
    end

    def from_omniauth(auth)
     # name = auth.info.name.split(" ")
     # user = User.where(email: auth.info.email).first 
     # user ||= User.create!(provider: auth.provider, uid: auth.uid, last: name[1], first: name[0], username: name, password: Devise.friendly_token[0,20])
     # user
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user| 
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.username = auth.info.name
        user.provider = auth.provider
        user.uid = auth.uid 
        user.first = auth.info.first_name 
        user.last = auth.info.last_name 
        user.save!(validate: false)
      end 
    end 
  end 

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
  skip_before_action :verify_authenticity_token, only: :facebook

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update 
    @user = User.find(params[:id])
    @user.attributes = user_params
    if @user.save validate: false 
      flash[:success] = "Updated user info."
    else 
      flash[:error] = "Unable to process update request."
    end 
    redirect_to current_user_path
  end 


  def me 
    @posts = Post.all.includes :likes, :comments, :image_attachment

  end 

  def cover
    current_user.cover.attach params[:user][:cover]
    current_user.save!(validate: false)
    if request.query_parameters[:redirect]
      redirect_to user_path current_user
    else
      redirect_to current_user_path
    end 
  end 

  def profile_picture 
    current_user.profile_picture.attach params[:user][:profile_picture]
    current_user.save!(validate: false)
    redirect_to current_user_path
  end 

  def show 
    @user = User.find(params[:id])
  end 

  private 
  
  def cover_parmas 
    params.require(:user).permit(:cover)
  end 

  def profile_picture_params 
    params.require(:user).permit(:profile_picture)
  end 

  def user_params 
    params.require(:user).permit(:username, :first, :last, :password, :email, :cover, :profile_picture)
  end
end 

app/helpers/users_helper.rb
module UsersHelper
  
  def formatted_name 
    return (self.first).capitalize + ' ' + (self.last).capitalize
  end 

  

  module ClassMethods 
    def genders 
      ['M','F','Custom']
    end 
  
    def from_omni_auth(auth)
    end 
    
    
  
    def default_profile_pic 
      "https://scontent-ort2-2.xx.fbcdn.net/v/t1.30497-1/c35.0.120.120a/p120x120/84241059_189132118950875_4138507100605120512_n.jpg?_nc_cat=1&ccb=2&_nc_sid=7206a8&_nc_ohc=p9OnxhNOvn4AX97lUx6&_nc_ht=scontent-ort2-2.xx&tp=27&oh=f09856717e5c2613710bf4e6d0b90b78&oe=603D3765"
    end 

  end 

  def self.included(subclass)
    subclass.extend(ClassMethods) 
  end 

end 

app/views/users/me.html.erb
<% if flash[:error] || flash[:sucess] %>
  <%= flash[:error] || flash[:sucess] %>
<% end %>
<div class="flex h-full justify-center">
  <div class="flex flex-col w-full sm:w-1/2 mx-10 sm:mx-0 md:w-1/4 lg:w-1/4  bg-white border border-solid border-gray-200 shadow-2xl rounded-md my-8">
    <div class="user-info m-2 flex-flex-col">
      <p class="font-semibold text-gray-700 text-2xl"> <%= current_user.formatted_name %> </p>
      <p class="text-sm font-light text-gray-600"> <%= '@' + current_user.username %> </p>
    </div>


    <!-- Profile display -->
    <div class="profile_picture mt-2 flex justify-center">
      <div class="picture w-16 h-16">
        <% if current_user.profile_picture.attached? %>
          <%= image_tag current_user.profile_picture, class: 'rounded-full border border-solid border-white w-full h-full' %>
        <% else %>
          <img x="0" y="0" class="picture rounded-full w-full h-full bg-black border border-solid border-white" height="100%" preserveAspectRatio="xMidYMid slice" width="100%" src=<%= User.default_profile_pic %> >
        <% end %>
      </div>
    </div>

    <!-- Change profile button -->
    <%= form_with model: current_user, method: :post, url: profile_picture_path, id: 'profile_form', class: 'change_profile flex justify-center pt-4' do |f|  %>
      <div id="me_profile" class="bg-blue-600 text-white px-2 py-0.5 rounded font-semibold cursor-pointer">Change profile pic</div>
      <%= f.file_field :profile_picture, class: 'hidden' %>
      <%= f.submit 'sub', class: "hidden" %>
    <% end %>


    <!-- Cover display -->

    <div class="cover mt-14 flex justify-center">
      <div class="picture w-28 h-20">
        <% if current_user.cover.attached? %>
          <%= image_tag current_user.cover, class: 'rounded-md border border-solid border-gray-200 w-full h-full' %>
        <% else %>
          <div class="cover bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500 h-2/4"></div>
        <% end %>
      </div>
    </div>

    <!-- Change cover button -->
    <%= form_with model: current_user, method: :post, url: cover_path, id: 'cover_form', class: 'change_profile flex justify-center pt-4' do |f| %>
      <div class="bg-blue-600 text-white px-2 py-0.5 rounded font-semibold cursor-pointer" id="me_cover">Change cover pic</div>
      <%= f.file_field :cover, class: 'hidden' %>
      <%= f.submit 'sub', class: 'hidden' %>
    <% end %>

    <!-- update uesr info form -->
    <%= form_with model: current_user,  class: 'flex flex-col mx-2 my-4' do |f| %>

      <div>
        <p class="font-light   text-xs text-gray-500">email</p>
        <%= f.email_field :email, class: 'w-full border border-solid border-gray-200 pl-2 py-1 rounded text-gray-600 outline-none focus:border-blue-400 mb-4' %>
      </div>

      <div>
        <p class="font-light   text-xs text-gray-500">password</p>
        <%= f.password_field :password, class: 'w-full border border-solid border-gray-200 pl-2 py-1 rounded text-gray-600 outline-none focus:border-blue-400 mb-4', placeholder: 'New password' %>
      </div>

      <div>
        <p class="font-light   text-xs text-gray-500">username</p>
        <%= f.text_field :username, class: 'w-full border border-solid border-gray-200 pl-2 py-1 rounded text-gray-600 outline-none focus:border-blue-400 mb-4' %>
      </div>

      <div class="names flex flex-col lg:flex-row justify-between mb-4">
        <div>
          <p class="font-light   text-xs text-gray-500">first name</p>
          <%= f.text_field :first, class: 'w-full border border-solid border-gray-200 outline-none focus:border-blue-400 rounded pl-2 py-1 text-gray-600' %>
        </div>

        <div>
          <p class="font-light   text-xs text-gray-500">last name</p>
          <%= f.text_field :last, class: 'w-full border border-solid border-gray-200 outline-none focus:border-blue-400 rounded pl-2 py-1 text-gray-600' %>
        </div>
      </div>

      <%= f.submit 'Update', class: 'py-0.5 px-1 bg-blue-600 text-white font-semibold border border-solid border-blue-300 rounded' %>

    <% end %>

  </div>
</div>
<%= javascript_pack_tag 'me_profile' %>
<%= javascript_pack_tag 'me_cover' %>

app/views/users/show.html.erb
<div class="flex justify-center  h-screen">
  <div class="flex flex-col w-full lg:w-2/4 md:w-3/4 h-full  ">

    <!-- cover form -->
    <% if @user.id == current_user.id %>
      <%= form_with model: @user, method: :post, url: cover_path(redirect: false), id: 'cover_form', class: 'flex items-center justify-center bg-blue-600 cursor-pointer rounded-sm py-1' do |f| %>
        <%= f.file_field :cover, class: "hidden" %>
        <div class="text-white font-semibold">Add cover</div>
        <%= f.submit '', class: 'hidden' %>
      <% end %>
    <% end %>

    <!-- cover display -->
    <div class="cover bg-gradient-to-r from-yellow-400 via-red-500 to-pink-500 h-2/4 rounded-b-md">
      <% if @user.cover.attached? %> 
        <%= image_tag @user.cover, class: 'w-full h-full rounded-b-md' %>
      <% end  %>
    </div>


    <!-- profile pic display -->
    <div class="flex justify-center ">
      <div id="profile_pic" class="profile_picture bg-black w-28 h-28 rounded-full border-2 border-solid border-white relative -top-20">
        <% if @user.profile_picture.attached? %>
          <%= image_tag @user.profile_picture, class: 'w-full h-full rounded-full' %>
        <% else %>
          <%= image_tag User.default_profile_pic, class: 'w-full h-full rounded-full' %>
        <% end %>

      </div>
    </div>

    <!-- me posts display -->
    <div class="w-full flex flex-col items-center relative -top-10">
      <% @user.posts.each do |post| %>
        <div class="w-2/3 flex flex-col justify-center bg-white rounded shadow my-2 border border-solid border-gray-200">
          
          <!-- Show user image, user's name and post dropdown -->
          <div class="user-name flex ml-4 mt-1 pt-2"> 
            <%= link_to @user_path do %>
              <img x="0" y="0" class="rounded-full h-7 w-7" height="100%" preserveAspectRatio="xMidYMid slice" width="100%" src=<%= User.default_profile_pic %> > 
            <% end %>
            <div class="ml-2  flex justify-between leading-5 w-full"> 
              <div class="flex flex-col">
                <span class="font-semibold hover:underline">
                  <%= link_to @user_path do %> 
                    <%= post.user.formatted_name %> 
                  <% end %>
                </span>
                
                <div class="text-xs text-gray-500"><%= post.when %></div>  
              </div>

              
              <% if post.user == @user %>
                <!-- Posts dropdown -->
                <div class="open-dropdown post-dropdown-toggle mr-2 rounded-full hover:bg-gray-200 h-10 w-10 flex justify-center items-center cursor-pointer select-none">
                  <div class="hidden post-dropdown flex flex-col w-1/6 h-24 bg-white rounded border border-solid border-gray-200 shadow absolute right-1/3 mr-10 mt-8">
      
                    <%= link_to edit_post_path(post, redirect: false), class: 'flex items-center mx-2 mt-2 rounded h-10 pl-2 hover:bg-gray-200 cursor-pointer' do %>
                      <svg class="inline w-6 h-6 " xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path>
                        </svg>
                        <p class="pl-4 font-medium">Edit post</p>
                    <% end %>

                    <%= link_to "posts/#{post.id}?redirect=false", method: :delete, class: 'flex items-center mx-2 rounded h-10 pl-2 hover:bg-gray-200 cursor-pointer' do %>
                      <svg class="inline w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                      </svg>
                      <p class="pl-4 font-medium">Delete post</p>
                    <% end %>
                  

                  </div>

                  <svg class="inline self-center w-6 h-6 text-secondarygray fill-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path>
                  </svg>

                </div>   

              <% end %>
            </div>   

            
          </div>

          <!-- Show post body -->
          <div class="user-post-body ml-4 mt-2 mb-2 mr-2 ">
            
            <div class="break-words"><%= post.body %></div>

          </div>

          <!-- Show image or video if any with for the post -->
          <div class="file-div">
            <% if post.image_attachment %>
              <div class="pb-2"><%= image_tag post.image, width: '100%' %></div>
            <% end %>
          </div>

        

          <div class="mx-4 flex justify-between">
            <div class="like-count">
              <% likes = post.likes.count %>
              <span class=" text-xs text-gray-400"> <%= likes > 0 ? likes.to_s + "#{likes > 1 ? " Likes" : " Like"}" : '' %>  </span>
            </div>

            <div class="comment-count">
              <% comments = post.comments.count %>
               <span class=" text-xs text-gray-400"> <%= comments > 0 ? comments.to_s + "#{comments > 1 ? " Comments" : " Comment"}" : '' %>  </span>
            </div>
          </div>

          <!-- Like or comment on a post -->
          <div class="flex mx-4 mb-2 justify-evenly ">
            <% if @user.liked_posts.include?(post) %>
              <%= link_to likes_path(post: post.id, redirect: false), class: "flex items-center rounded hover:bg-gray-100 w-full justify-center cursor-pointer", method: :delete do %>
                <svg class="inline w-6 h-6 mr-1 mb-1 self-center  text-blue-600 stroke-2 stroke-current text-secondarygray" fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z"></path>
                </svg>
                <div class="font-medium text-blue-700 text-lg  ml-2">Like</div>
              <% end %>
            <% else %>
              <%= link_to likes_path(post: post.id, redirect: false), class: "flex items-center rounded hover:bg-gray-100 w-full justify-center cursor-pointer" do %>
                <svg class="inline w-6 h-6 mr-1 mb-1 self-center text-gray-400 stroke-2 stroke-current text-secondarygray" fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                  <path d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z"></path>
                </svg>
                <div class="font-medium text-gray-700 text-lg  ml-2">Like</div>
              <% end %>
            <% end %>
          
            
            <div class="flex items-center w-full justify-center rounded hover:bg-gray-100 cursor-pointer">
              <svg class="inline w-6 h-6 mr-1 mb-1 text-gray-700" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 8h2a2 2 0 012 2v6a2 2 0 01-2 2h-2v4l-4-4H9a1.994 1.994 0 01-1.414-.586m0 0L11 14h4a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2v4l.586-.586z"></path>
              </svg>
              <div class="font-medium text-gray-700 text-lg  ml-2">Comment</div>
            </div>

           
          </div>

          <!-- Make a form to create comments -->

          <%= form_with model: [post,Comment.new], method: :get, class: 'flex mx-4' do |f| %>
            <%= f.text_field :body, class: "px-2 border border-solid border-gray-300 rounded-3xl bg-gray-100 outline-none w-full", placeholder: 'Comment' %>
            <%= f.hidden_field :redirect, value: false %>

          <% end %>

          <!-- Show all post comments -->
          <div class="all-comments flex flex-col mx-4 mt-2 space-y-2 py-2">
            
            
           
            <% post.comments.each do |comment| %>
              <div class="flex items-center">
                <div><img x="0" y="0" class="rounded-full h-5 w-5" height="100%" preserveAspectRatio="xMidYMid slice" width="100%" src=<%= User.default_profile_pic %> ></div>
                <div class="pl-1 text-xs font-light text-gray-600 w-full flex justify-between"> 
                  <p class="truncate"> <%= @user.username %> </p> 
                  <% if comment.user == @user %>
                    <div class="comment-dropdown-toggler rounded-full hover:bg-gray-200 cursor-pointer">
                      <svg class="inline self-center w-6 h-6 text-secondarygray fill-current" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h.01M12 12h.01M19 12h.01M6 12a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0zm7 0a1 1 0 11-2 0 1 1 0 012 0z"></path>
                      </svg>
                      <div class="comment-dropdown hidden absolute bg-white border border-solid border-gray-300 h-16 w-1/4 md:w-2/6 lg:w-1/12 right-1/3 mr-10 -mt-8 rounded flex flex-col justify-center">
                        <%= link_to post_comment_path(post, comment), method: :delete, class: 'hover:bg-gray-200 rounded text-center mx-1' do %>
                          <span class="text-lg font-semibold">Delete</span>
                        <% end %>
                        <%= link_to edit_post_comment_path(post,comment, redirect: false), class: 'hover:bg-gray-200 text-center rounded mx-1' do %>
                          <span class="text-lg font-semibold">Edit</span>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                    
                </div>
              </div>
              <% if action_name = "edit" && comment.id.to_i == params[:id].to_i %>
                <%= form_with model: [post,comment], class: 'flex mx-4' do |f| %>
                  <%= f.text_field :body, class: "px-2 border border-solid border-gray-300 rounded-3xl bg-gray-100 outline-none w-full", placeholder: 'Comment' %>
                  <%= f.hidden_field :redirect, value: false %>
                <% end %>
              <% else %>
                <div class="font-light bg-gray-100 rounded-md px-1"> <%= comment.body %> </div>
              <% end %>
            <% end %>
        
               

                


          </div>

          

        </div>
      <% end %>
    </div>

  </div>
</div>

<%= javascript_pack_tag 'post' %>
<%= javascript_pack_tag 'comment' %>
<%= javascript_pack_tag 'cover' %>